; [pytest]
; pythonpath = .
; markers =
;     selenium: mark tests as Selenium tests
;     playwright: mark tests as Playwright tests
; addopts = -v
; [pytest]
; testpaths = Suites


[pytest]
pythonpath = .
markers =
    selenium: mark tests as Selenium tests
    playwright: mark tests as Playwright tests
addopts = -v --tb=short --maxfail=1 --cache-clear
testpaths = tests/selenium 
python_files = test_*.py
python_classes = Test*
python_functions = test_*
